services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /Users/dingjiaming/Desktop/DingJiaMing/front-end/juejin/Nest-Secret-Guide/Chapter-76/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123456
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/dingjiaming/Desktop/DingJiaMing/front-end/juejin/Nest-Secret-Guide/Chapter-76/data/redis:/data
